### ISSUE TITLE
Delete and accent characters don't work on first keyboard load

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#133]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Something that was noticed for the current main version of the application is that accent character keys (`ä`, `ö`, etc) and the delete key don't work on first keyboard load. This is reproducible by:

- Building the application
- Opening an app like a messenger and experimenting with the keyboard
    - Accent characters and delete don't work
- Going out of the messenger and going back in and experimenting with the keyboard
    - Accent characters and delete will work

Would be great if this could be figured out, as this is the last major bug that's meaning that the keyboard isn't functional as a system one :)

### Device type

Emulator is a Pixel 8 Pro

### Versions

Current development branch

**Comment by angrezichatterbox** [comment]
I would work on this issue and try to fix the bug.

**Comment by andrewtavis** [comment]
Thanks for picking this up, @angrezichatterbox!

**Comment by angrezichatterbox** [comment]
I am not exactly sure if I can replicate this error. These are the two cases which I have tried so far: 

- I built the app on the existing virtual device and used the German keyboard. I was able to use it on the first load itself. 
- I built the app on a new virtual device I have created and ran the app. I was still able to use the keyboard keys specified properly. 

Would it be that it would have been fixed during the period somehow? I did see it during the call but cannot replicate it now. Could you check whether it's still replicable for you?

**Comment by andrewtavis** [comment]
I deleted my device emulator, remade a new Pixel 8 Pro Android 35 emulator and I'm still getting the errors we were seeing 🤔 Any further steps that I could take to see if this is a local problem for me? Clear some caches?

**Comment by angrezichatterbox** [comment]
> I deleted my device emulator, remade a new Pixel 8 Pro Android 35 emulator and I'm still getting the errors we were seeing 🤔 Any further steps that I could take to see if this is a local problem for me? Clear some caches?

I don't think it would be a local problem since you have done it on a new emulator as well. But for some reason, those keys seem to work for me in the new emulator. I tried using the same emulator that you have used as well.

**Comment by angrezichatterbox** [comment]
@andrewtavis When you are free could  you check if the keyboard are still crashing for you. Now that the keyboards code are refactored to use a single abstract class. We may not be getting crashes as earlier since earlier different keyboards had different code and there used to be crashes due to some issues.

**Comment by andrewtavis** [comment]
Great call here, @angrezichatterbox! This issue is now resolved post the refactoring 😊
